# Generated by Django 4.2.3 on 2023-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
